name: Run Tests & Publish Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:  # ← Добавьте эту секцию
      contents: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 + Allure
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          allure-version: '2.29.0'

      - name: Run tests (headless)
        run: mvn test -Dheadless=true -Dallure.skip=true --batch-mode
        env:
          HEADLESS: "true"

      - name: Generate Allure report
        run: |
          allure generate target/allure-results --clean -o target/allure-report
        if: always()

      - name: Deploy report to GitHub Pages