name: Run Tests & Publish Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Обязательно добавьте этот шаг!

      - name: Install Allure CLI
        run: npm install -g @allure-framework/allure-commandline@2.29.0

      - name: Run tests (headless)
        run: mvn test -Dheadless=true -Dallure.skip=true --batch-mode
        env:
          HEADLESS: "true"

      - name: Generate Allure report
        run: |
          allure generate target/allure-results --clean -o target/allure-report
        if: always()

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          publish_branch: gh-pages
          force_orphan: true